import { Global, Injectable, Module } from "@nestjs/common";
import { DeleteObjectCommand, GetObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { createHmac, timingSafeEqual } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { env } from "../config/env";

/** Storage seam: local disk, or any S3-compatible bucket (Cloudflare R2, MinIO, AWS S3). */
export interface StorageDriver {
  put(key: string, data: Buffer): Promise<void>;
  get(key: string): Promise<Buffer>;
  delete(key: string): Promise<void>;
}

class LocalDiskDriver implements StorageDriver {
  private root = path.resolve(env().STORAGE_LOCAL_DIR);

  /** Keys are generated by the server, but never trust a path: refuse anything that escapes the root. */
  private resolve(key: string) {
    const full = path.resolve(this.root, key);
    if (!full.startsWith(this.root + path.sep)) throw new Error("Invalid storage key");
    return full;
  }
  async put(key: string, data: Buffer) {
    const full = this.resolve(key);
    await mkdir(path.dirname(full), { recursive: true });
    await writeFile(full, data, { mode: 0o600 });
  }
  get(key: string) {
    return readFile(this.resolve(key));
  }
  async delete(key: string) {
    await rm(this.resolve(key), { force: true });
  }
}

/** Same three methods over an S3-compatible bucket. `client` is injectable so tests need no network. */
export class S3Driver implements StorageDriver {
  constructor(
    private bucket: string,
    private client: Pick<S3Client, "send">,
  ) {}

  async put(key: string, data: Buffer) {
    await this.client.send(new PutObjectCommand({ Bucket: this.bucket, Key: key, Body: data }));
  }
  async get(key: string) {
    const res = await this.client.send(new GetObjectCommand({ Bucket: this.bucket, Key: key }));
    if (!res.Body) throw new Error("Empty object");
    return Buffer.from(await res.Body.transformToByteArray());
  }
  async delete(key: string) {
    await this.client.send(new DeleteObjectCommand({ Bucket: this.bucket, Key: key }));
  }
}

export function createDriver(): StorageDriver {
  const e = env();
  if (e.STORAGE_DRIVER === "local") return new LocalDiskDriver();
  if (!e.S3_BUCKET || !e.S3_ACCESS_KEY || !e.S3_SECRET_KEY) {
    throw new Error("STORAGE_DRIVER=s3 needs S3_BUCKET, S3_ACCESS_KEY and S3_SECRET_KEY");
  }
  const client = new S3Client({
    region: e.S3_REGION,
    endpoint: e.S3_ENDPOINT || undefined,
    forcePathStyle: true,
    credentials: { accessKeyId: e.S3_ACCESS_KEY, secretAccessKey: e.S3_SECRET_KEY },
  });
  return new S3Driver(e.S3_BUCKET, client);
}

/** Virus-scan hook. The default does nothing; plug ClamAV or a cloud scanner in here without touching callers. */
export interface VirusScanner {
  scan(data: Buffer, filename: string): Promise<{ clean: boolean; reason?: string }>;
}

const SIGNATURES: { mime: string; test: (b: Buffer) => boolean }[] = [
  { mime: "image/jpeg", test: (b) => b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff },
  {
    mime: "image/png",
    test: (b) => b.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])),
  },
  {
    mime: "image/webp",
    test: (b) => b.subarray(0, 4).toString("latin1") === "RIFF" && b.subarray(8, 12).toString("latin1") === "WEBP",
  },
  { mime: "application/pdf", test: (b) => b.subarray(0, 5).toString("latin1") === "%PDF-" },
];

/** The real type is decided from the file's bytes, never from the client-supplied name or content type. */
export function sniffMime(data: Buffer): string | null {
  return SIGNATURES.find((s) => s.test(data))?.mime ?? null;
}

@Injectable()
export class StorageService {
  driver: StorageDriver = createDriver();
  scanner: VirusScanner = { scan: async () => ({ clean: true }) };

  private signingKey = createHmac("sha256", "file-urls").update(env().JWT_ACCESS_SECRET).digest();

  private mac(fileId: string, exp: number) {
    return createHmac("sha256", this.signingKey).update(`${fileId}.${exp}`).digest("hex");
  }

  /** Short-lived URL: documents are never public, they are served only with a valid, unexpired signature. */
  signedUrl(fileId: string, ttlSeconds = env().FILE_URL_TTL_SECONDS) {
    const exp = Math.floor(Date.now() / 1000) + ttlSeconds;
    return { url: `/files/${fileId}/content?e=${exp}&s=${this.mac(fileId, exp)}`, expiresInSeconds: ttlSeconds };
  }

  verify(fileId: string, exp: number, sig: string): boolean {
    if (!Number.isFinite(exp) || exp < Date.now() / 1000) return false;
    const a = Buffer.from(this.mac(fileId, exp));
    const b = Buffer.from(sig);
    return a.length === b.length && timingSafeEqual(a, b);
  }
}

@Global()
@Module({ providers: [StorageService], exports: [StorageService] })
export class StorageModule {}
